version: '3.8'

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: medisync
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: medisync_redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass medisync1234
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: